'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0hmllEtyv4K
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export default function ChatApps() {
  return (
    <div className="flex flex-col h-[90vh] max-h-[800px] w-full max-w-[600px] mx-auto bg-background rounded-2xl shadow-lg overflow-hidden">
      <header className="flex items-center gap-4 bg-primary text-primary-foreground px-6 py-4 shrink-0">
        <Avatar className="w-10 h-10 border-2 border-primary-foreground">
          <AvatarImage src="/placeholder-user.jpg" alt="Chatbot" />
          <AvatarFallback>CB</AvatarFallback>
        </Avatar>
        <div className="text-lg font-medium">Chatbot</div>
      </header>
      <div className="flex-1 overflow-auto p-6 space-y-4 h-[500px]">
        <div className="flex items-start gap-4">
          <Avatar className="w-8 h-8 border-2 border-muted">
            <AvatarImage src="/placeholder-user.jpg" alt="User" />
            <AvatarFallback>YO</AvatarFallback>
          </Avatar>
          <div className="bg-muted rounded-lg p-4 max-w-[70%]">
            <p>Hi there! How can I assist you today?</p>
          </div>
        </div>
        <div className="flex items-start gap-4 justify-end">
          <div className="bg-primary text-primary-foreground rounded-lg p-4 max-w-[70%]">
            <p>I'm looking for some information on your product features.</p>
          </div>
          <Avatar className="w-8 h-8 border-2 border-primary">
            <AvatarImage src="/placeholder-user.jpg" alt="Chatbot" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
        </div>
        <div className="flex items-start gap-4">
          <Avatar className="w-8 h-8 border-2 border-muted">
            <AvatarImage src="/placeholder-user.jpg" alt="User" />
            <AvatarFallback>YO</AvatarFallback>
          </Avatar>
          <div className="bg-muted rounded-lg p-4 max-w-[70%]">
            <p>Great, can you tell me more about the key features?</p>
          </div>
        </div>
        <div className="flex items-start gap-4 justify-end">
          <div className="bg-primary text-primary-foreground rounded-lg p-4 max-w-[70%]">
            <p>
              Absolutely! Our product has a range of powerful features, including real-time analytics, automated
              workflows, and seamless integrations.
            </p>
          </div>
          <Avatar className="w-8 h-8 border-2 border-primary">
            <AvatarImage src="/placeholder-user.jpg" alt="Chatbot" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
        </div>
      </div>
      <div className="bg-muted px-6 py-4 flex items-center gap-2">
        <Input
          type="text"
          placeholder="Type your message..."
          className="flex-1 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
        />
        <Button className="rounded-lg px-4 py-2 text-sm font-medium">Send</Button>
      </div>
      <div className="absolute bottom-4 right-4">
        <Button
          variant="ghost"
          size="icon"
          className="rounded-full bg-primary text-primary-foreground hover:bg-primary/90"
        >
          <PlusIcon className="w-6 h-6" />
          <span className="sr-only">New Conversation</span>
        </Button>
      </div>
    </div>
  )
}

function PlusIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
